#!/system/bin/sh

sleep 3
# See: Documentation/arm/msm/boot.txt
boot_reason=`cat /proc/sys/kernel/boot_reason`
# REBOOT if boot_reason&1==1 (power button long press)
((($boot_reason&1)==1)) && reboot

# Start CHARGER after boot_reason to prevent charging anims
exec /sbin/chargerlogo
