#!/system/bin/sh

#0x01 -- keyboard power on
#0x02 -- RTC alarm
#0x04 -- cable power on
#0x08 -- SMPL
#0x10 -- Watch Dog timeout
#0x20 -- USB charger
#0x40 -- Wall charger
#0xFF -- error reading power_on_status value

# boot_reason & 1: power button is pressed

# REBOOT if reason&1==1
boot_reason=`cat /proc/sys/kernel/boot_reason`
((($boot_reason&1)==1)) && reboot

# CHARGER
echo conservative > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
echo 102 > /sys/class/leds/lcd-backlight/brightness
echo 255 > /sys/class/leds/button-backlight/brightness
